version: '3'
services:
 nginx:
  image: nginx
  volumes:
   - './nginx/nginx.conf:/etc/nginx/nginx.conf'
  ports:
   - 80:80
  restart: on-failure

 server:
  build: ./server
  ports:
   - 3000:3000
  restart: on-failure
 